### ISSUE TITLE
Create test environment

### ISSUE THREAD

**Issue by alpertandogan** [damianofalcioni/Websocket-Smart-Card-Signer#3]
Hi i installed your solution. 
Works well . 

I try to compile your java using netbean ?
Which version or which IDe i have to use compile JNA and Iaik

http://www.java2s.com/Code/JarDownload/iaik/iaik.jar.zip

**Comment by damianofalcioni** [comment]
Hi,
please use the iaik and jacknji11 dependencies in my repository to compile it:
- [https://github.com/damianofalcioni/pkcs11wrapper](https://github.com/damianofalcioni/pkcs11wrapper)
- [https://github.com/damianofalcioni/jacknji11](https://github.com/damianofalcioni/jacknji11)

all the rest are Maven dependencies so the version is automatically managed.

PS: I use Eclipse. Do not know how it work in Netbean.

**Comment by alpertandogan** [comment]
I try to compile Eclipse . I can import your dependecies but after i m not a expert to compile output as JNLP ..

My problem is your JNLP works return correct result to using websock but . When  i make a second file it returns first one (again) and second one ... It is add all send file to JNLP  ..I make a modification in js file before send using websocket i clear all values .. I check in network log in chrome i send correct file(only one file base64 ) but it return all files add by add ... 

Best regards.

**Comment by damianofalcioni** [comment]
Maven compile only the project in a JAR file.
The JNLP file have to be created manually or taken the one in the jnlp_test_page folder.
