### ISSUE TITLE
How to use it for signing pdf in React application

### ISSUE THREAD

**Issue by nirmalpatra27** [damianofalcioni/Websocket-Smart-Card-Signer#32]
I want to sign a pdf in the React application. Kindly help with the sample code

**Comment by nirmalpatra27** [comment]
Thanks in advance

**Comment by damianofalcioni** [comment]
Hi,
you have to convert the https://github.com/damianofalcioni/Websocket-Smart-Card-Signer/blob/master/examples/websocket_smartcard_signer_lib.js as an ESM module first (just add an export websocket_smartcard_signer at the end) and then you can import the library in your react script as usual and use the functions as shown in https://github.com/damianofalcioni/Websocket-Smart-Card-Signer/blob/master/examples/websocket_smartcard_signer_test_page.html
