### ISSUE TITLE
non compila

### ISSUE THREAD

**Issue by EmilioRusso77** [damianofalcioni/Websocket-Smart-Card-Signer#33]
Ciao Damiano, maven install non và, a causa di questa dipendenza https://mvnrepository.com/artifact/iaik.pkcs/pkcs11-wrapper che punta ad un repository http://nexus.emergya.es/nexus/content/repositories/public/ offline, come possiamo risolvere?

Grazie

**Comment by damianofalcioni** [comment]
Ciao,
come scritto nel readme, https://github.com/damianofalcioni/pkcs11wrapper è una dipendenza, come anche https://github.com/damianofalcioni/jacknji11. 
Fai maven install di queste prima e poi non dovresti avere problemi a compilare.
