### ISSUE TITLE
Error while signing with the custom token WatchdataProxkey

### ISSUE THREAD

**Issue by ski14** [damianofalcioni/Websocket-Smart-Card-Signer#5]
Connection to  C:\windows\System32\SignatureP11.dll
log4j:WARN No appenders could be found for logger (org.pkcs11.jacknji11.C).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
java.lang.Exception: Can not download CRL from: https://www.ncodesolutions.com/repository/ncodeca14.crl
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target...
Connection to  C:\windows\System32\SignatureP11.dll
java.lang.Exception: Impossible to perform a valid signature with the following certificate and libraries
Certificate: 'CN=xxx, SERIALNUMBER=xxx, ST=xxx, OID.2.5.4.17=xxx, OU="xxx,CID - xxx", OID.2.5.4.20=xxx, O=xxx, C=xxx'

**Comment by damianofalcioni** [comment]
Hi,
as the log say: the CRL can not be downloaded from [https://www.ncodesolutions.com/repository/ncodeca14.crl](https://www.ncodesolutions.com/repository/ncodeca14.crl).
Check if from the machine the url is reachable or other network issues like a proxy or firewall.
The affected line to debug is [HERE](https://github.com/damianofalcioni/Websocket-Smart-Card-Signer/blob/5f7df7b5222c88f9add01111fb91cdc1132a81b1/src/main/java/df/sign/utils/X509Utils.java#L156)

**Comment by ski14** [comment]
Hi,the url from the machine is reachable.
I have tried disable the firewall it still give the same error
Thank You
