### ISSUE TITLE
Cannot Sign Using WatchdataProxy Token "SignatureP11.dll"

### ISSUE THREAD

**Issue by ski14** [damianofalcioni/Websocket-Smart-Card-Signer#6]
The following error occured
java.lang.Exception: Can not download the CRL from: https://www.ncodesolutions.com/repository/ncodeca14.crl
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Have tried diable the firewall still the same and  It can access the url directly from the browser..Please Help :)

**Comment by damianofalcioni** [comment]
Hi,
the problem may not be only related to the CRL Download but to the fact that the public root of your certificate authority is not in your default java keystore. Just search the error "sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target" on google. Is a standard java signature verification failing error.

**Comment by ski14** [comment]
Whats is the password for the keystore.jks?

**Comment by damianofalcioni** [comment]
[https://lmgtfy.com/?q=java+keystore+default+password](https://lmgtfy.com/?q=java+keystore+default+password) ;)
