### ISSUE TITLE
Signing Document in a browser

### ISSUE THREAD

**Issue by Origi27** [damianofalcioni/Websocket-Smart-Card-Signer#9]
In the Jnlp_test page,it send only the hello world word right?
Can we sign pdf document in the browser and upload somewhere in another folder?
and how do you call the function to select file and sign in the webpage?
Thank You

**Comment by damianofalcioni** [comment]
Hi,
to sign a pdf document you have to first read it in a HTML Input field and then provide it to the engine as done in the Hello World example. The file selection is just a matter of JS code.

**Comment by Origi27** [comment]
I'm not much into programming..Can you be specific where to put and to call?
Thank You

**Comment by damianofalcioni** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsDataURL

**Comment by Origi27** [comment]
Thanks, but its confusing me like after selecting the file how do you call
the function from the server to perform the signature?
Thank You

**Comment by damianofalcioni** [comment]
https://github.com/damianofalcioni/Websocket-Smart-Card-Signer/blob/5f7df7b5222c88f9add01111fb91cdc1132a81b1/jnlp_test_page/websocket_smartcard_signer_test_page.html#L15

**Comment by Origi27** [comment]
Thank you and one thing i notice when i start a server and i perform sign
locally and select a file once its working fine but when i perform sign
locally again without restarting the server it ask me two or three times to
save the same file

**Comment by damianofalcioni** [comment]
Try to debug here:
https://github.com/damianofalcioni/Websocket-Smart-Card-Signer/blob/5f7df7b5222c88f9add01111fb91cdc1132a81b1/src/main/java/df/sign/SignFactory.java#L88

**Comment by Origi27** [comment]
Thanks
Is it possible if i browse a file in html and sign that document and save
by default in a particular folder without choosing where to save

**Comment by damianofalcioni** [comment]
if you sign using the web page then with the signed file you can or download locally or upload where you want (of course you need an uploading service) via JS
